run:
  timeout: 1m
  skip-dirs:
    - scripts

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - asciicheck
    - errorlint
    - depguard
    - goconst
    - makezero
    - predeclared
    - gocritic
    - importas
